$(document).ready(function(){
	var prompt = new promptFunc();
	$('.confirm').click(function(){
		if($('.newPassword').val()!=$('.confirmPassword').val()){
			prompt.init({
				type:"",
				text:"新密码不一致",
			});
			return;
		}
		if($('.oldPassword').val()==$('.newPassword').val()){
			prompt.init({
				type:"",
				text:"新密码和原密码不能相同",
			});
			return;
		}
		var code1= /^([0-9a-zA-Z-_.]){6,18}$/;
		if(!code1.test($('.newPassword').val())){
			prompt.init({
				type:"",
				text:"新密码输入格式有误",
			});
			return;
		}
		$.ajax({
			type:"POST",
			url:"/yich/SendKey",
			 dataType:"json",
			 async:false,
			success:function(data){
				setMaxDigits(130);
				var key = new RSAKeyPair(data.empoent,"",data.module);
				var oldResult = encryptedString(key, $('.oldPassword').val());
				var newResult = encryptedString(key, $('.newPassword').val());
				$.ajax({
					type: 'POST',
					url: '/yich/PhoneChangePwd',
					dataType: 'json',
					data: "{\"opwd\":\""+oldResult+"\",\"npwd\":\""+newResult+"\"}",
					async:false,
					success: function(res){
						if(typeof (res.userId)!='undefined'){
						    fwh_authorize(res.userId);
						}
						if(res.result == 1){
							prompt.init({
								type:"",
								text:"修改成功",
							});
							setTimeout(function(){
								window.location.replace('/yich/wapservice/dist/html/business_center_setting.html');
							},1000);
						}else{
							prompt.init({
								type:"",
								text:"原密码不正确",
							});
						}
					},
					error: function(res){
						prompt.init({
							type:"",
							text:"修改失败",
						});
					}
				})
			},
			error:function(res){
				prompt.init({
					type:"",
					text:"修改失败",
				});
			}
		});
	})
	//实时监听验证码输入
	$('.oldPassword').bind('input propertychange',function(){
		if($(this).val()&&$('.newPassword').val()&&$('.confirmPassword').val()){
			$('.confirm').removeAttr('disabled');
			$('.confirm').removeClass('confirmForbid');
			$('.confirm').addClass('confirmClick');
		}else{
			$('.confirm').attr('disabled',true);
			$('.confirm').removeClass('confirmClick');
			$('.confirm').addClass('confirmForbid');
		}
	});
	$('.newPassword').bind('input propertychange',function(){
		if($(this).val()&&$('.oldPassword').val()&&$('.confirmPassword').val()){
			$('.confirm').removeAttr('disabled');
			$('.confirm').removeClass('confirmForbid');
			$('.confirm').addClass('confirmClick');
		}else{
			$('.confirm').attr('disabled',true);
			$('.confirm').removeClass('confirmClick');
			$('.confirm').addClass('confirmForbid');
		}
	});
	$('.confirmPassword').bind('input propertychange',function(){
		if($(this).val()&&$('.newPassword').val()&&$('.oldPassword').val()){
			$('.confirm').removeAttr('disabled');
			$('.confirm').removeClass('confirmForbid');
			$('.confirm').addClass('confirmClick');
		}else{
			$('.confirm').attr('disabled',true);
			$('.confirm').removeClass('confirmClick');
			$('.confirm').addClass('confirmForbid');
		}
	});
	$('.oldPassword').bind('input propertychange',function(){
		$('.oldPasswordDelete').show();
		$('.oldPasswordEyes').show();
	});
	$('.oldPassword').focus(function(){
		if($('.oldPassword').val()){
			$('.oldPasswordDelete').show();
			$('.oldPasswordEyes').show();
		}
	});
	$('.oldPassword').blur(function(){
		$('.oldPasswordDelete').hide();
		$('.oldPasswordEyes').hide();
	});
	$('.newPassword').bind('input propertychange',function(){
		$('.newPasswordDelete').show();
		$('.newPasswordEyes').show();
	});
	$('.newPassword').focus(function(){
		if($('.newPassword').val()){
			$('.newPasswordDelete').show();
			$('.newPasswordEyes').show();
		}
	});
	$('.newPassword').blur(function(){
		$('.newPasswordDelete').hide();
		$('.newPasswordEyes').hide();
	});
	$('.confirmPassword').bind('input propertychange',function(){
		$('.confirmPasswordDelete').show();
		$('.confirmPasswordEyes').show();
	});
	$('.confirmPassword').focus(function(){
		if($('.confirmPassword').val()){
			$('.confirmPasswordDelete').show();
			$('.confirmPasswordEyes').show();
		}
	});
	$('.confirmPassword').blur(function(){
		$('.confirmPasswordDelete').hide();
		$('.confirmPasswordEyes').hide();
	});
	$('.oldPasswordDelete').click(function(event){
		$('.oldPassword').val('');
	});
	$('.newPasswordDelete').click(function(){
		$('.newPassword').val('');
	});
	$('.confirmPasswordDelete').click(function(){
		$('.confirmPassword').val('');
	});
	$('.oldPasswordDelete').mousedown(function(event){
		event.preventDefault();
	});
	$('.newPasswordDelete').mousedown(function(event){
		event.preventDefault();
	});
	$('.confirmPasswordDelete').mousedown(function(event){
		event.preventDefault();
	});
	$('.oldPasswordEyes').click(function(){
		if($('.oldPassword').attr('type')=='password'){
			$('.oldPassword').attr('type','text');
			$('.newPassword').attr('type','text');
			$('.confirmPassword').attr('type','text');
			$('.oldPasswordEyes').removeClass('icon-nolook');
			$('.oldPasswordEyes').addClass('icon-look');
			$('.newPasswordEyes').removeClass('icon-nolook');
			$('.newPasswordEyes').addClass('icon-look');
			$('.confirmPasswordEyes').removeClass('icon-nolook');
			$('.confirmPasswordEyes').addClass('icon-look');
		}else{
			$('.oldPassword').attr('type','password');
			$('.newPassword').attr('type','password');
			$('.confirmPassword').attr('type','password');
			$('.oldPasswordEyes').removeClass('icon-look');
			$('.oldPasswordEyes').addClass('icon-nolook');
			$('.newPasswordEyes').removeClass('icon-look');
			$('.newPasswordEyes').addClass('icon-nolook');
			$('.confirmPasswordEyes').removeClass('icon-look');
			$('.confirmPasswordEyes').addClass('icon-nolook');
		}
	});
	$('.oldPasswordEyes').mousedown(function(event){
		event.preventDefault();
	});
	$('.newPasswordEyes').click(function(){
		if($('.newPassword').attr('type')=='password'){
			$('.oldPassword').attr('type','text');
			$('.newPassword').attr('type','text');
			$('.confirmPassword').attr('type','text');
			$('.oldPasswordEyes').removeClass('icon-nolook');
			$('.oldPasswordEyes').addClass('icon-look');
			$('.newPasswordEyes').removeClass('icon-nolook');
			$('.newPasswordEyes').addClass('icon-look');
			$('.confirmPasswordEyes').removeClass('icon-nolook');
			$('.confirmPasswordEyes').addClass('icon-look');
		}else{
			$('.oldPassword').attr('type','password');
			$('.newPassword').attr('type','password');
			$('.confirmPassword').attr('type','password');
			$('.oldPasswordEyes').removeClass('icon-look');
			$('.oldPasswordEyes').addClass('icon-nolook');
			$('.newPasswordEyes').removeClass('icon-look');
			$('.newPasswordEyes').addClass('icon-nolook');
			$('.confirmPasswordEyes').removeClass('icon-look');
			$('.confirmPasswordEyes').addClass('icon-nolook');
		}
	});
	$('.newPasswordEyes').mousedown(function(event){
		event.preventDefault();
	});
	$('.confirmPasswordEyes').click(function(){
		if($('.confirmPassword').attr('type')=='password'){
			$('.oldPassword').attr('type','text');
			$('.newPassword').attr('type','text');
			$('.confirmPassword').attr('type','text');
			$('.oldPasswordEyes').removeClass('icon-nolook');
			$('.oldPasswordEyes').addClass('icon-look');
			$('.newPasswordEyes').removeClass('icon-nolook');
			$('.newPasswordEyes').addClass('icon-look');
			$('.confirmPasswordEyes').removeClass('icon-nolook');
			$('.confirmPasswordEyes').addClass('icon-look');
		}else{
			$('.oldPassword').attr('type','password');
			$('.newPassword').attr('type','password');
			$('.confirmPassword').attr('type','password');
			$('.oldPasswordEyes').removeClass('icon-look');
			$('.oldPasswordEyes').addClass('icon-nolook');
			$('.newPasswordEyes').removeClass('icon-look');
			$('.newPasswordEyes').addClass('icon-nolook');
			$('.confirmPasswordEyes').removeClass('icon-look');
			$('.confirmPasswordEyes').addClass('icon-nolook');
		}
	});
	$('.confirmPasswordEyes').mousedown(function(event){
		event.preventDefault();
	});
});